
development:
  adapter: mysql2
  reconnect: false
  database: concentration_game_development
  pool: 5
  host: localhost

test:
  adapter: mysql2
  reconnect: false
  database: concentration_game_test
  pool: 5
  host: localhost

production:
  adapter: mysql2
  reconnect: false
  database: concentration_game_production
  pool: 5
  host: localhost
  username: root
  password: password
